import {
  filterUpcomingMarketEvents,
  MARKET_EVENT_REFRESH_INTERVAL_HOURS,
  StaticMarketEventFeed,
  type LiveCatalyst,
  type MarketEvent,
} from "@/lib/integrations/market-events";

export const marketEventsRefreshLabel = `${MARKET_EVENT_REFRESH_INTERVAL_HOURS}h refresh`;

function formatEventDate(dateValue: string) {
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(`${dateValue}T12:00:00Z`));
}

function getNextWeekdayDateValue(targetWeekday: number, now = new Date()) {
  const current = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const delta = (targetWeekday - current.getUTCDay() + 7) % 7;
  current.setUTCDate(current.getUTCDate() + delta);
  return current.toISOString().slice(0, 10);
}

const nextJoblessClaimsDate = getNextWeekdayDateValue(4);

const scheduledMarketEvents: MarketEvent[] = [
  {
    event: "US Nonfarm Payrolls",
    dateValue: "2026-07-02",
    date: formatEventDate("2026-07-02"),
    time: "08:30 ET",
    region: "US",
    importance: "Critical",
    affected: ["Fed cuts rates at next meeting", "BTC breaks ATH this quarter", "US recession in 2026"],
    type: "Macro",
    source: "BLS Employment Situation",
    sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
    sourceKind: "economic-calendar",
    why: "Can rapidly reprice labor softness, Fed expectations, and crypto volatility.",
  },
  {
    event: "US CPI Inflation Release",
    dateValue: "2026-07-14",
    date: formatEventDate("2026-07-14"),
    time: "08:30 ET",
    region: "US",
    importance: "Critical",
    affected: ["Fed cuts rates at next meeting", "BTC breaks ATH this quarter", "Inflation falls below 3% in 2026"],
    type: "Macro",
    source: "BLS CPI Calendar",
    sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
    sourceKind: "economic-calendar",
    why: "Can rapidly reprice Fed expectations and crypto volatility.",
  },
  {
    event: "US Treasury Coupon Auction Window",
    dateValue: null,
    date: "Date TBA",
    time: "Auction time TBA",
    region: "US",
    importance: "High",
    affected: ["10Y yield closes above 4.75%", "Fed cuts rates at next meeting", "BTC breaks ATH this quarter"],
    type: "Rates",
    source: "TreasuryDirect Upcoming Auctions",
    sourceUrl: "https://www.treasurydirect.gov/auctions/upcoming/",
    sourceKind: "economic-calendar",
    why: "Auction announcements and tails can pressure duration, risk assets, and macro prediction markets.",
  },
  {
    event: "US PPI Inflation Release",
    dateValue: "2026-07-15",
    date: formatEventDate("2026-07-15"),
    time: "08:30 ET",
    region: "US",
    importance: "High",
    affected: ["Fed cuts rates at next meeting", "Inflation falls below 3% in 2026", "BTC breaks ATH this quarter"],
    type: "Macro",
    source: "BLS PPI Calendar",
    sourceUrl: "https://www.bls.gov/ppi/",
    sourceKind: "economic-calendar",
    why: "Producer inflation can confirm or challenge CPI-driven Fed repricing.",
  },
  {
    event: "Initial Jobless Claims",
    dateValue: nextJoblessClaimsDate,
    date: formatEventDate(nextJoblessClaimsDate),
    time: "08:30 ET expected",
    region: "US",
    importance: "Medium",
    affected: ["Fed cuts rates at next meeting", "US recession in 2026", "Continuing claims rise in June"],
    type: "Labor",
    source: "US Department of Labor",
    sourceUrl: "https://www.dol.gov/ui/data.pdf",
    sourceKind: "economic-calendar",
    why: "Weekly labor weakness can move rate-cut and recession probabilities before monthly payrolls confirm.",
  },
  {
    event: "FOMC Rate Decision",
    dateValue: "2026-07-29",
    date: formatEventDate("2026-07-29"),
    time: "14:00 ET",
    region: "US",
    importance: "Critical",
    affected: ["Fed cuts rates at next meeting", "BTC breaks ATH this quarter", "US recession in 2026"],
    type: "Central bank",
    source: "Federal Reserve FOMC Calendar",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceKind: "economic-calendar",
    why: "Impacts liquidity conditions, risk assets, and rate-sensitive markets.",
  },
  {
    event: "Fed Chair Press Conference",
    dateValue: "2026-07-29",
    date: formatEventDate("2026-07-29"),
    time: "14:30 ET expected",
    region: "US",
    importance: "High",
    affected: ["Fed cuts rates at next meeting", "BTC breaks ATH this quarter", "Powell signals policy pivot"],
    type: "Central bank",
    source: "Federal Reserve FOMC Calendar",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceKind: "economic-calendar",
    why: "Forward guidance can move probabilities even when the rate decision itself is priced.",
  },
  {
    event: "SOL ETF SEC Review Window",
    dateValue: null,
    date: "Q3 2026 review window",
    time: "Regulatory window",
    region: "US",
    importance: "High",
    affected: ["SOL ETF approved in 2026", "SOL outperforms ETH this quarter", "Crypto ETF expansion in 2026"],
    type: "ETF calendar",
    source: "SEC Filings",
    sourceUrl: "https://www.sec.gov/edgar/search/",
    sourceKind: "etf-calendar",
    why: "Can reprice approval probabilities and smart money positioning.",
  },
  {
    event: "NVIDIA Q2 FY2027 Earnings Window",
    dateValue: null,
    date: "Late August 2026 expected",
    time: "Post-market expected",
    region: "US",
    importance: "High",
    affected: ["Nvidia market cap above $5T", "AI regulation bill passes in 2026", "AI compute capex accelerates"],
    type: "Corporate",
    source: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/financial-info/financial-reports/default.aspx",
    sourceKind: "crypto-catalyst",
    why: "AI earnings can reprice compute demand, risk appetite, and AI-linked prediction markets.",
  },
  {
    event: "US Midterm Election",
    dateValue: "2026-11-03",
    date: "November 3, 2026",
    time: "Election day",
    region: "US",
    importance: "Critical",
    affected: ["Republicans keep House in 2026", "Democrats win Senate in 2026", "US policy volatility after midterms"],
    type: "Geopolitical",
    source: "FEC Election Calendar",
    sourceUrl: "https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2026-reporting-dates/federal-election-activity-periods-each-state-2026/",
    sourceKind: "news-monitoring",
    why: "Election-control probabilities can move fiscal, regulatory, crypto, and geopolitical policy markets.",
  },
];

export function getUpcomingMarketEvents(now = new Date()) {
  return filterUpcomingMarketEvents(scheduledMarketEvents, now);
}

export const upcomingEvents: MarketEvent[] = getUpcomingMarketEvents();

export const liveCatalysts: LiveCatalyst[] = [
  {
    title: "US-Iran Escalation Risk",
    category: "Geopolitical",
    importance: "High",
    lastUpdate: "18 minutes ago",
    latestDevelopment: "White House decision risk remains elevated after ceasefire and negotiation headlines.",
    source: "AP",
    sourceUrl: "https://apnews.com/article/cac5206df0f0c7b79fe9321c08d63096",
    timeline: [
      {
        time: "18m ago",
        headline: "Trump decision risk remains the central variable around the Iran ceasefire path.",
        source: "AP",
        sourceUrl: "https://apnews.com/article/cac5206df0f0c7b79fe9321c08d63096",
      },
      {
        time: "43m ago",
        headline: "Israeli-Lebanon escalation threat added pressure to U.S.-Iran negotiations.",
        source: "Axios",
        sourceUrl: "https://www.axios.com/2026/06/01/trump-netanyahu-lebanon-israel-bomb-beirut",
      },
      {
        time: "2h ago",
        headline: "Energy-risk desks continued tracking Strait of Hormuz and oil-volatility exposure.",
        source: "Market Intelligence",
        sourceUrl: "https://www.eia.gov/petroleum/",
      },
      {
        time: "5h ago",
        headline: "Defense and oil-linked narratives outperformed broad risk-on crypto narratives.",
        source: "OracleX Flow Model",
        sourceUrl: "https://polymarket.com/",
      },
    ],
    affectedMarkets: ["Oil closes above $90 in 2026", "BTC breaks ATH this quarter", "Fed cuts rates at next meeting", "US-Iran ceasefire holds through Q3"],
    oracleXAssessment: "Geopolitical risk premium increasing.",
    why: "Escalation risk can move probability markets before formal diplomatic or military confirmation arrives.",
    historicalImpact: ["Similar Middle East escalation windows increased oil and risk-off positioning within 24h.", "Similar energy-shock headlines compressed rate-cut confidence when inflation risk rose.", "Similar geopolitical catalysts produced short-lived BTC downside before liquidity conditions became decisive."],
    reactions: ["Higher geopolitical tail-risk pricing", "Liquidity stress in risk-on markets", "Risk-off movement across crypto and macro-linked markets"],
    narratives: ["Middle East escalation", "Energy security", "Election foreign policy"],
    flows: "Defensive positioning rising in macro-linked markets; crypto flows remain mixed.",
    smartMoney: "Selective hedging from geopolitics-focused wallets, no broad capitulation.",
    watchNext: ["White House briefing language", "Iran response", "oil volatility", "defense-sector relative strength", "crypto liquidity reaction"],
  },
  {
    title: "July Fed Repricing Window",
    category: "Macro / Rates",
    importance: "Critical",
    lastUpdate: "1 hour ago",
    latestDevelopment: "NFP, CPI, PPI, Treasury supply, and the July FOMC decision cluster into the next macro repricing window.",
    source: "Federal Reserve",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    timeline: [
      {
        time: "1h ago",
        headline: "July 28-29 FOMC meeting is the next anchor event for rate-cut probabilities.",
        source: "Federal Reserve",
        sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
      },
      {
        time: "3h ago",
        headline: "July 14 CPI date keeps inflation risk concentrated before the Fed decision.",
        source: "BLS",
        sourceUrl: "https://www.bls.gov/schedule/news_release/cpi.htm",
      },
      {
        time: "6h ago",
        headline: "TreasuryDirect upcoming auctions remain the source for the next coupon supply window.",
        source: "US Treasury",
        sourceUrl: "https://www.treasurydirect.gov/auctions/upcoming/",
      },
      {
        time: "1d ago",
        headline: "July 2 payrolls opens the labor-market leg of the repricing window.",
        source: "BLS",
        sourceUrl: "https://www.bls.gov/schedule/news_release/empsit.htm",
      },
    ],
    affectedMarkets: ["Fed cuts rates at next meeting", "BTC breaks ATH this quarter", "10Y yield closes above 4.75%", "US recession in 2026"],
    oracleXAssessment: "Macro conditions remain unsupportive despite narrative acceleration.",
    why: "The July data cluster can reset liquidity expectations faster than crypto-native catalysts.",
    historicalImpact: ["Similar CPI/FOMC clusters increased BTC volatility within 24h of the first inflation print.", "Similar Treasury auction tails pushed rate-sensitive prediction markets toward tighter policy outcomes.", "Similar NFP surprises moved recession and rate-cut probabilities before equity-market confirmation."],
    reactions: ["Rate-cut probability compression", "Higher BTC implied volatility", "Rotation from crypto beta into macro hedges"],
    narratives: ["Fed path", "Inflation persistence", "Treasury supply"],
    flows: "Macro-sensitive wallets are reducing directional leverage into CPI and FOMC.",
    smartMoney: "Top macro wallets remain defensive until CPI confirms disinflation.",
    watchNext: ["NFP wage growth", "CPI core services", "10Y auction tail", "Powell press conference language", "BTC liquidity gap"],
  },
  {
    title: "SOL ETF SEC Review Window",
    category: "ETF Calendar",
    importance: "High",
    lastUpdate: "2 hours ago",
    latestDevelopment: "SOL ETF review timing remains the highest-conviction crypto regulatory event window in the terminal.",
    source: "SEC Filing",
    sourceUrl: "https://www.sec.gov/edgar/search/",
    timeline: [
      {
        time: "2h ago",
        headline: "Issuer and docket monitoring flagged Q3 2026 as the next material review window.",
        source: "SEC Filing",
        sourceUrl: "https://www.sec.gov/edgar/search/",
      },
      {
        time: "4h ago",
        headline: "SOL approval-market liquidity improved while broader altcoin liquidity stayed selective.",
        source: "Polymarket",
        sourceUrl: "https://polymarket.com/",
      },
      {
        time: "8h ago",
        headline: "Linked wallets added directional exposure across SOL ETF probability markets.",
        source: "OracleX Prediction Market Analytics",
        sourceUrl: "https://polymarket.com/",
      },
      {
        time: "1d ago",
        headline: "ETF sympathy basket narrowed toward SOL and ETH-linked markets.",
        source: "OracleX Flow Model",
        sourceUrl: "https://polymarket.com/",
      },
    ],
    affectedMarkets: ["SOL ETF approved in 2026", "SOL outperforms ETH this quarter", "Crypto ETF expansion in 2026", "BTC breaks ATH this quarter"],
    oracleXAssessment: "Market pricing still lags wallet accumulation.",
    why: "ETF timelines can quickly reprice approval markets when wallet flow, issuer signals, and liquidity align.",
    historicalImpact: ["Similar ETF windows preceded multi-point probability expansions before final agency action.", "Similar issuer-commentary cycles pulled liquidity into adjacent crypto approval markets.", "Similar SEC docket events increased smart-money concentration before retail narrative acceleration."],
    reactions: ["Higher SOL approval probability", "Short-term liquidity stress", "Narrative expansion across ETF sympathy markets"],
    narratives: ["ETF approval cycle", "Institutional crypto access", "Issuer filing window"],
    flows: "$3.8M directional YES accumulation detected across linked wallets.",
    smartMoney: "14 linked wallets active with 2.7x baseline entry size.",
    watchNext: ["SEC docket updates", "issuer amendments", "ETF analyst commentary", "SOL spot liquidity", "probability divergence"],
  },
  {
    title: "AI Compute Earnings Shock",
    category: "Corporate / AI",
    importance: "High",
    lastUpdate: "3 hours ago",
    latestDevelopment: "NVIDIA's latest earnings print reinforced AI capex strength and kept AI-linked prediction markets bid.",
    source: "NVIDIA Investor Relations",
    sourceUrl: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-First-Quarter-Fiscal-2027/default.aspx",
    timeline: [
      {
        time: "3h ago",
        headline: "AI infrastructure demand remains the dominant cross-asset corporate catalyst.",
        source: "NVIDIA Investor Relations",
        sourceUrl: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-First-Quarter-Fiscal-2027/default.aspx",
      },
      {
        time: "7h ago",
        headline: "AI policy markets saw renewed attention after compute-demand commentary.",
        source: "OracleX Narrative Monitor",
        sourceUrl: "https://investor.nvidia.com/financial-info/financial-reports/default.aspx",
      },
      {
        time: "12h ago",
        headline: "AI-capex basket stayed firm while crypto beta remained macro-dependent.",
        source: "Market Intelligence",
        sourceUrl: "https://www.nasdaq.com/market-activity/stocks/nvda",
      },
      {
        time: "1d ago",
        headline: "Agentic AI and data-center narratives expanded into regulatory and infrastructure markets.",
        source: "NVIDIA Newsroom",
        sourceUrl: "https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
      },
    ],
    affectedMarkets: ["Nvidia market cap above $5T", "AI regulation bill passes in 2026", "AI compute capex accelerates", "Agent OS launches before 2027"],
    oracleXAssessment: "AI narrative strength is real, but macro liquidity still controls risk appetite.",
    why: "AI earnings can move equity risk, compute policy, and agent-market probabilities before legislation or product deadlines arrive.",
    historicalImpact: ["Similar NVIDIA earnings beats expanded AI-adjacent prediction market attention within one session.", "Similar compute-demand shocks lifted infrastructure narratives before policy markets caught up.", "Similar AI earnings cycles strengthened risk-on beta only when macro conditions were supportive."],
    reactions: ["Higher attention in AI regulation markets", "Compute infrastructure probability expansion", "Risk-on sympathy if rates remain contained"],
    narratives: ["AI capex", "Compute controls", "Agent regulation"],
    flows: "Narrative participation +38%; institutional policy accounts +22%.",
    smartMoney: "Partial confirmation from AI-specialist wallets; macro accounts remain cautious.",
    watchNext: ["Q2 FY2027 earnings date", "hyperscaler capex guidance", "AI export-control headlines", "NVDA relative strength", "policy-market liquidity"],
  },
];

export const marketEventFeeds = {
  economicCalendar: new StaticMarketEventFeed("economic-calendar-adapter", "economic-calendar", upcomingEvents.filter((event) => event.sourceKind === "economic-calendar")),
  etfCalendar: new StaticMarketEventFeed("etf-calendar-adapter", "etf-calendar", upcomingEvents.filter((event) => event.sourceKind === "etf-calendar")),
  geopoliticalMonitoring: new StaticMarketEventFeed("geopolitical-monitoring-adapter", "news-monitoring", upcomingEvents.filter((event) => event.sourceKind === "news-monitoring")),
  cryptoCatalysts: new StaticMarketEventFeed("crypto-catalyst-adapter", "crypto-catalyst", liveCatalysts),
};
